# Generated by Django 4.2.2 on 2024-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('math_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stats_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('compsci_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('english_marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
