# Generated by Django 4.2.2 on 2024-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('rated_as', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(max_length=50)),
                ('stars', models.TextField()),
                ('streaming_on', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
